[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "bash start.sh"
healthcheckPath = "/api/v1/products/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
